// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SellerMetrics.Infrastructure.Persistence;

#nullable disable

namespace SellerMetrics.Infrastructure.Migrations
{
    [DbContext(typeof(SellerMetricsDbContext))]
    [Migration("20251201175637_AddEbayIntegration")]
    partial class AddEbayIntegration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SellerMetrics.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SellerMetrics.Domain.Entities.BusinessExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessLine")
                        .HasColumnType("integer");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTaxDeductible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ReceiptPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ServiceJobId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Vendor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessLine");

                    b.HasIndex("Category");

                    b.HasIndex("ExpenseDate");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ServiceJobId");

                    b.HasIndex("ExpenseDate", "BusinessLine");

                    b.HasIndex("ExpenseDate", "Category");

                    b.ToTable("BusinessExpenses", (string)null);
                });

            modelBuilder.Entity("SellerMetrics.Domain.Entities.ComponentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcquiredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int?>("ServiceJobId")
                        .HasColumnType("integer");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("StorageLocationId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ComponentTypeId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Quantity");

                    b.HasIndex("ServiceJobId");

                    b.HasIndex("Status");

                    b.HasIndex("StorageLocationId");

                    b.ToTable("ComponentItems", (string)null);
                });

            modelBuilder.Entity("SellerMetrics.Domain.Entities.ComponentQuantityAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdjustedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Adjustment")
                        .HasColumnType("integer");

                    b.Property<int>("ComponentItemId")
                        .HasColumnType("integer");

                    b.Property<int>("NewQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("PreviousQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("AdjustedAt");

                    b.HasIndex("ComponentItemId");

                    b.ToTable("ComponentQuantityAdjustments", (string)null);
                });

            modelBuilder.Entity("SellerMetrics.Domain.Entities.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultExpenseCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemType")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("ComponentTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 1, 17, 56, 36, 622, DateTimeKind.Utc).AddTicks(7697),
                            DefaultExpenseCategory = "Parts & Materials",
                            Description = "Random Access Memory modules",
                            IsDeleted = false,
                            IsSystemType = true,
                            Name = "RAM",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 1, 17, 56, 36, 622, DateTimeKind.Utc).AddTicks(8374),
                            DefaultExpenseCategory = "Parts & Materials",
                            Description = "Solid State Drives",
                            IsDeleted = false,
                            IsSystemType = true,
                            Name = "SSD",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 1, 17, 56, 36, 622, DateTimeKind.Utc).AddTicks(8376),
                            DefaultExpenseCategory = "Parts & Materials",
                            Description = "Hard Disk Drives",
                            IsDeleted = false,
                            IsSystemType = true,
                            Name = "HDD",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 1, 17, 56, 36, 622, DateTimeKind.Utc).AddTicks(8378),
                            DefaultExpenseCategory = "Parts & Materials",
                            Description = "Power Supply Units (PSU)",
                            IsDeleted = false,
                            IsSystemType = true,
                            Name = "Power Supply",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 12, 1, 17, 56, 36, 622, DateTimeKind.Utc).AddTicks(8379),
                            DefaultExpenseCategory = "Parts & Materials",
                            Description = "Central Processing Units",
                            IsDeleted = false,
                            IsSystemType = true,
                            Name = "CPU",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 12, 1, 17, 56, 36, 622, DateTimeKind.Utc).AddTicks(8380),
                            DefaultExpenseCategory = "Parts & Materials",
                            Description = "System motherboards",
                            IsDeleted = false,
                            IsSystemType = true,
                            Name = "Motherboard",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 12, 1, 17, 56, 36, 622, DateTimeKind.Utc).AddTicks(8381),
                            DefaultExpenseCategory = "Parts & Materials",
                            Description = "GPUs and video cards",
                            IsDeleted = false,
                            IsSystemType = true,
                            Name = "Graphics Card",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 12, 1, 17, 56, 36, 622, DateTimeKind.Utc).AddTicks(8382),
                            DefaultExpenseCategory = "Parts & Materials",
                            Description = "Network interface cards and adapters",
                            IsDeleted = false,
                            IsSystemType = true,
                            Name = "Network Card",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 12, 1, 17, 56, 36, 622, DateTimeKind.Utc).AddTicks(8383),
                            DefaultExpenseCategory = "Parts & Materials",
                            Description = "Fans, heatsinks, and cooling systems",
                            IsDeleted = false,
                            IsSystemType = true,
                            Name = "Cooling",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 12, 1, 17, 56, 36, 622, DateTimeKind.Utc).AddTicks(8384),
                            DefaultExpenseCategory = "Parts & Materials",
                            Description = "Computer cases and enclosures",
                            IsDeleted = false,
                            IsSystemType = true,
                            Name = "Case",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 12, 1, 17, 56, 36, 622, DateTimeKind.Utc).AddTicks(8385),
                            DefaultExpenseCategory = "Parts & Materials",
                            Description = "Cables and connectors",
                            IsDeleted = false,
                            IsSystemType = true,
                            Name = "Cables",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 12, 1, 17, 56, 36, 622, DateTimeKind.Utc).AddTicks(8386),
                            DefaultExpenseCategory = "Parts & Materials",
                            Description = "Keyboards, mice, and other peripherals",
                            IsDeleted = false,
                            IsSystemType = true,
                            Name = "Peripherals",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 12, 1, 17, 56, 36, 622, DateTimeKind.Utc).AddTicks(8387),
                            DefaultExpenseCategory = "Parts & Materials",
                            Description = "Other components",
                            IsDeleted = false,
                            IsSystemType = true,
                            Name = "Other",
                            SortOrder = 99
                        });
                });

            modelBuilder.Entity("SellerMetrics.Domain.Entities.EbayOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BuyerUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EbayItemId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EbayOrderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("FulfillmentStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("InventoryItemId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LegacyOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("OrderDate");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "EbayOrderId")
                        .IsUnique();

                    b.ToTable("EbayOrders", (string)null);
                });

            modelBuilder.Entity("SellerMetrics.Domain.Entities.EbayUserCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AccessTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EbayUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EbayUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EncryptedAccessToken")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("EncryptedRefreshToken")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Scopes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("IsConnected");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("EbayUserCredentials", (string)null);
                });

            modelBuilder.Entity("SellerMetrics.Domain.Entities.EstimatedTaxPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfirmationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Quarter")
                        .HasColumnType("integer");

                    b.Property<int>("TaxYear")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsPaid", "DueDate");

                    b.HasIndex("TaxYear", "Quarter")
                        .IsUnique();

                    b.ToTable("EstimatedTaxPayments");
                });

            modelBuilder.Entity("SellerMetrics.Domain.Entities.FiscalYearConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FiscalYearStartMonth")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("FiscalYearConfigurations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FiscalYearStartMonth = 1,
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("SellerMetrics.Domain.Entities.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Condition")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("EbayListingId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EbaySku")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("InternalSku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ListedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SoldDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("StorageLocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EbayListingId");

                    b.HasIndex("EbaySku");

                    b.HasIndex("InternalSku")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Status");

                    b.HasIndex("StorageLocationId");

                    b.HasIndex("Title");

                    b.ToTable("InventoryItems", (string)null);
                });

            modelBuilder.Entity("SellerMetrics.Domain.Entities.IrsMileageRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CharitableRate")
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MedicalRate")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("StandardRate")
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EffectiveDate");

                    b.HasIndex("Year");

                    b.HasIndex("Year", "EffectiveDate");

                    b.ToTable("IrsMileageRates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CharitableRate = 0.14m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            MedicalRate = 0.21m,
                            Notes = "IRS standard mileage rate for 2024",
                            StandardRate = 0.67m,
                            Year = 2024
                        },
                        new
                        {
                            Id = 2,
                            CharitableRate = 0.14m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            MedicalRate = 0.21m,
                            Notes = "IRS standard mileage rate for 2025",
                            StandardRate = 0.70m,
                            Year = 2025
                        });
                });

            modelBuilder.Entity("SellerMetrics.Domain.Entities.MileageEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessLine")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRoundTrip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Miles")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("OdometerEnd")
                        .HasColumnType("integer");

                    b.Property<int?>("OdometerStart")
                        .HasColumnType("integer");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ServiceJobId")
                        .HasColumnType("integer");

                    b.Property<string>("StartLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("TripDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BusinessLine");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ServiceJobId");

                    b.HasIndex("TripDate");

                    b.HasIndex("TripDate", "BusinessLine");

                    b.ToTable("MileageEntries", (string)null);
                });

            modelBuilder.Entity("SellerMetrics.Domain.Entities.RevenueEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EbayOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("EntryType")
                        .HasColumnType("integer");

                    b.Property<int?>("InventoryItemId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("ServiceJobId")
                        .HasColumnType("integer");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WaveInvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EbayOrderId");

                    b.HasIndex("EntryType");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ServiceJobId");

                    b.HasIndex("Source");

                    b.HasIndex("TransactionDate");

                    b.HasIndex("WaveInvoiceNumber");

                    b.HasIndex("Source", "TransactionDate");

                    b.ToTable("RevenueEntries", (string)null);
                });

            modelBuilder.Entity("SellerMetrics.Domain.Entities.ServiceJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerContact")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("JobNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WaveInvoiceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerName");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("JobNumber")
                        .IsUnique();

                    b.HasIndex("ReceivedDate");

                    b.HasIndex("Status");

                    b.HasIndex("WaveInvoiceId");

                    b.ToTable("ServiceJobs", (string)null);
                });

            modelBuilder.Entity("SellerMetrics.Domain.Entities.StorageLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name");

                    b.HasIndex("ParentId");

                    b.HasIndex("ParentId", "SortOrder");

                    b.ToTable("StorageLocations", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SellerMetrics.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SellerMetrics.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SellerMetrics.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SellerMetrics.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SellerMetrics.Domain.Entities.BusinessExpense", b =>
                {
                    b.HasOne("SellerMetrics.Domain.Entities.ServiceJob", "ServiceJob")
                        .WithMany()
                        .HasForeignKey("ServiceJobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("SellerMetrics.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<int>("BusinessExpenseId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("USD")
                                .HasColumnName("Currency");

                            b1.HasKey("BusinessExpenseId");

                            b1.ToTable("BusinessExpenses");

                            b1.WithOwner()
                                .HasForeignKey("BusinessExpenseId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("ServiceJob");
                });

            modelBuilder.Entity("SellerMetrics.Domain.Entities.ComponentItem", b =>
                {
                    b.HasOne("SellerMetrics.Domain.Entities.ComponentType", "ComponentType")
                        .WithMany("Items")
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SellerMetrics.Domain.Entities.ServiceJob", "ServiceJob")
                        .WithMany("Components")
                        .HasForeignKey("ServiceJobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SellerMetrics.Domain.Entities.StorageLocation", "StorageLocation")
                        .WithMany()
                        .HasForeignKey("StorageLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("SellerMetrics.Domain.ValueObjects.Money", "UnitCost", b1 =>
                        {
                            b1.Property<int>("ComponentItemId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("UnitCostAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("USD")
                                .HasColumnName("UnitCostCurrency");

                            b1.HasKey("ComponentItemId");

                            b1.ToTable("ComponentItems");

                            b1.WithOwner()
                                .HasForeignKey("ComponentItemId");
                        });

                    b.Navigation("ComponentType");

                    b.Navigation("ServiceJob");

                    b.Navigation("StorageLocation");

                    b.Navigation("UnitCost")
                        .IsRequired();
                });

            modelBuilder.Entity("SellerMetrics.Domain.Entities.ComponentQuantityAdjustment", b =>
                {
                    b.HasOne("SellerMetrics.Domain.Entities.ComponentItem", "ComponentItem")
                        .WithMany("Adjustments")
                        .HasForeignKey("ComponentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentItem");
                });

            modelBuilder.Entity("SellerMetrics.Domain.Entities.EbayOrder", b =>
                {
                    b.HasOne("SellerMetrics.Domain.Entities.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SellerMetrics.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SellerMetrics.Domain.ValueObjects.Money", "AdditionalFees", b1 =>
                        {
                            b1.Property<int>("EbayOrderId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("AdditionalFeesAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("USD")
                                .HasColumnName("AdditionalFeesCurrency");

                            b1.HasKey("EbayOrderId");

                            b1.ToTable("EbayOrders");

                            b1.WithOwner()
                                .HasForeignKey("EbayOrderId");
                        });

                    b.OwnsOne("SellerMetrics.Domain.ValueObjects.Money", "FinalValueFee", b1 =>
                        {
                            b1.Property<int>("EbayOrderId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("FinalValueFeeAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("USD")
                                .HasColumnName("FinalValueFeeCurrency");

                            b1.HasKey("EbayOrderId");

                            b1.ToTable("EbayOrders");

                            b1.WithOwner()
                                .HasForeignKey("EbayOrderId");
                        });

                    b.OwnsOne("SellerMetrics.Domain.ValueObjects.Money", "GrossSale", b1 =>
                        {
                            b1.Property<int>("EbayOrderId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("GrossSaleAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("USD")
                                .HasColumnName("GrossSaleCurrency");

                            b1.HasKey("EbayOrderId");

                            b1.ToTable("EbayOrders");

                            b1.WithOwner()
                                .HasForeignKey("EbayOrderId");
                        });

                    b.OwnsOne("SellerMetrics.Domain.ValueObjects.Money", "PaymentProcessingFee", b1 =>
                        {
                            b1.Property<int>("EbayOrderId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PaymentProcessingFeeAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("USD")
                                .HasColumnName("PaymentProcessingFeeCurrency");

                            b1.HasKey("EbayOrderId");

                            b1.ToTable("EbayOrders");

                            b1.WithOwner()
                                .HasForeignKey("EbayOrderId");
                        });

                    b.OwnsOne("SellerMetrics.Domain.ValueObjects.Money", "ShippingActual", b1 =>
                        {
                            b1.Property<int>("EbayOrderId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ShippingActualAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("USD")
                                .HasColumnName("ShippingActualCurrency");

                            b1.HasKey("EbayOrderId");

                            b1.ToTable("EbayOrders");

                            b1.WithOwner()
                                .HasForeignKey("EbayOrderId");
                        });

                    b.OwnsOne("SellerMetrics.Domain.ValueObjects.Money", "ShippingPaid", b1 =>
                        {
                            b1.Property<int>("EbayOrderId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ShippingPaidAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("USD")
                                .HasColumnName("ShippingPaidCurrency");

                            b1.HasKey("EbayOrderId");

                            b1.ToTable("EbayOrders");

                            b1.WithOwner()
                                .HasForeignKey("EbayOrderId");
                        });

                    b.Navigation("AdditionalFees")
                        .IsRequired();

                    b.Navigation("FinalValueFee")
                        .IsRequired();

                    b.Navigation("GrossSale")
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("PaymentProcessingFee")
                        .IsRequired();

                    b.Navigation("ShippingActual")
                        .IsRequired();

                    b.Navigation("ShippingPaid")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SellerMetrics.Domain.Entities.EbayUserCredential", b =>
                {
                    b.HasOne("SellerMetrics.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SellerMetrics.Domain.Entities.EstimatedTaxPayment", b =>
                {
                    b.OwnsOne("SellerMetrics.Domain.ValueObjects.Money", "AmountPaid", b1 =>
                        {
                            b1.Property<int>("EstimatedTaxPaymentId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("AmountPaid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("PaidCurrency");

                            b1.HasKey("EstimatedTaxPaymentId");

                            b1.ToTable("EstimatedTaxPayments");

                            b1.WithOwner()
                                .HasForeignKey("EstimatedTaxPaymentId");
                        });

                    b.OwnsOne("SellerMetrics.Domain.ValueObjects.Money", "EstimatedAmount", b1 =>
                        {
                            b1.Property<int>("EstimatedTaxPaymentId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("EstimatedAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("EstimatedCurrency");

                            b1.HasKey("EstimatedTaxPaymentId");

                            b1.ToTable("EstimatedTaxPayments");

                            b1.WithOwner()
                                .HasForeignKey("EstimatedTaxPaymentId");
                        });

                    b.Navigation("AmountPaid")
                        .IsRequired();

                    b.Navigation("EstimatedAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("SellerMetrics.Domain.Entities.InventoryItem", b =>
                {
                    b.HasOne("SellerMetrics.Domain.Entities.StorageLocation", "StorageLocation")
                        .WithMany()
                        .HasForeignKey("StorageLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("SellerMetrics.Domain.ValueObjects.Money", "Cogs", b1 =>
                        {
                            b1.Property<int>("InventoryItemId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("CogsAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("USD")
                                .HasColumnName("CogsCurrency");

                            b1.HasKey("InventoryItemId");

                            b1.ToTable("InventoryItems");

                            b1.WithOwner()
                                .HasForeignKey("InventoryItemId");
                        });

                    b.Navigation("Cogs")
                        .IsRequired();

                    b.Navigation("StorageLocation");
                });

            modelBuilder.Entity("SellerMetrics.Domain.Entities.MileageEntry", b =>
                {
                    b.HasOne("SellerMetrics.Domain.Entities.ServiceJob", "ServiceJob")
                        .WithMany()
                        .HasForeignKey("ServiceJobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ServiceJob");
                });

            modelBuilder.Entity("SellerMetrics.Domain.Entities.RevenueEntry", b =>
                {
                    b.HasOne("SellerMetrics.Domain.Entities.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SellerMetrics.Domain.Entities.ServiceJob", "ServiceJob")
                        .WithMany()
                        .HasForeignKey("ServiceJobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("SellerMetrics.Domain.ValueObjects.Money", "Fees", b1 =>
                        {
                            b1.Property<int>("RevenueEntryId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("FeesAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("USD")
                                .HasColumnName("FeesCurrency");

                            b1.HasKey("RevenueEntryId");

                            b1.ToTable("RevenueEntries");

                            b1.WithOwner()
                                .HasForeignKey("RevenueEntryId");
                        });

                    b.OwnsOne("SellerMetrics.Domain.ValueObjects.Money", "GrossAmount", b1 =>
                        {
                            b1.Property<int>("RevenueEntryId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("GrossAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("USD")
                                .HasColumnName("GrossCurrency");

                            b1.HasKey("RevenueEntryId");

                            b1.ToTable("RevenueEntries");

                            b1.WithOwner()
                                .HasForeignKey("RevenueEntryId");
                        });

                    b.Navigation("Fees")
                        .IsRequired();

                    b.Navigation("GrossAmount")
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("ServiceJob");
                });

            modelBuilder.Entity("SellerMetrics.Domain.Entities.StorageLocation", b =>
                {
                    b.HasOne("SellerMetrics.Domain.Entities.StorageLocation", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SellerMetrics.Domain.Entities.ComponentItem", b =>
                {
                    b.Navigation("Adjustments");
                });

            modelBuilder.Entity("SellerMetrics.Domain.Entities.ComponentType", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SellerMetrics.Domain.Entities.ServiceJob", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("SellerMetrics.Domain.Entities.StorageLocation", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
